### ISSUE TITLE
Trouble building from source...

### ISSUE THREAD

**Issue by chadacious** [lvcabral/brs-emu#95]
Seems like there either some steps that are not documented, or that the tests are not working.

On a windows machine, following the steps from the docs to build from source, initially:
- yarn build works. Generates the lib folder and brsEmu.js as well as some other js files. But all tests failed.
- I tried `yarn add brs` because it seemed it needed that, and then I got some tests to pass.
- Saw all the snapshot tests were failing so tried `yarn test -u` and got more tests to pass.
- I Notice that failing tests are looking for a lib folder that doesn't seem to exist. And that is where I'm stuck.

```
 FAIL  test/brsTypes/Boolean.test.js
  ● Test suite failed to run

    Cannot find module '../../lib/brsTypes' from 'test/brsTypes/Boolean.test.js'

    > 1 | const BrsTypes = require("../../lib/brsTypes");
        | ^
      2 |
      3 | describe("Boolean", () => {
      4 |     test("true equals true", () => {

      at Resolver.resolveModule (node_modules/jest-resolve/build/index.js:306:11)
      at Object.<anonymous> (test/brsTypes/Boolean.test.js:1:1)
```

So here are my test results:
```
Test Suites: 57 failed, 34 passed, 91 total
Tests:       3 failed, 276 passed, 279 total
Snapshots:   172 passed, 172 total
Time:        13.68 s
Ran all test suites.
```
Tried it on linux but had problems with the --env.NODE_ENV command in the package.json scripts.

Any advice on getting things up and running? I am super interested in this project and the potential for single code-base UI development.

**Comment by chadacious** [comment]
Another issue is that the `bin/cli.js` is not included in the github repo, which some of the tests refer to. I found an old one in one of your original commits and that seems to resolve a few more tests.

**Comment by chadacious** [comment]
Alright believe I understand now. It seems that you don't really intend for these tests to work actually. That seems to be something that was carried over from the brs project and is not really something you are keeping up on.

Now that I understand that I think I am good to move on. Unless you have some other advice, you can close the issue at your convenience.
